/** International dial codes — all major countries & territories */
export const COUNTRIES = [
	{ name: "Afghanistan", code: "AF", dial: "93" },
	{ name: "Albania", code: "AL", dial: "355" },
	{ name: "Algeria", code: "DZ", dial: "213" },
	{ name: "Argentina", code: "AR", dial: "54" },
	{ name: "Australia", code: "AU", dial: "61" },
	{ name: "Austria", code: "AT", dial: "43" },
	{ name: "Bahrain", code: "BH", dial: "973" },
	{ name: "Bangladesh", code: "BD", dial: "880" },
	{ name: "Belgium", code: "BE", dial: "32" },
	{ name: "Brazil", code: "BR", dial: "55" },
	{ name: "Canada", code: "CA", dial: "1" },
	{ name: "Chile", code: "CL", dial: "56" },
	{ name: "China", code: "CN", dial: "86" },
	{ name: "Colombia", code: "CO", dial: "57" },
	{ name: "Croatia", code: "HR", dial: "385" },
	{ name: "Czech Republic", code: "CZ", dial: "420" },
	{ name: "Denmark", code: "DK", dial: "45" },
	{ name: "Egypt", code: "EG", dial: "20" },
	{ name: "Ethiopia", code: "ET", dial: "251" },
	{ name: "Finland", code: "FI", dial: "358" },
	{ name: "France", code: "FR", dial: "33" },
	{ name: "Germany", code: "DE", dial: "49" },
	{ name: "Ghana", code: "GH", dial: "233" },
	{ name: "Greece", code: "GR", dial: "30" },
	{ name: "Hong Kong", code: "HK", dial: "852" },
	{ name: "Hungary", code: "HU", dial: "36" },
	{ name: "Iceland", code: "IS", dial: "354" },
	{ name: "India", code: "IN", dial: "91" },
	{ name: "Indonesia", code: "ID", dial: "62" },
	{ name: "Iran", code: "IR", dial: "98" },
	{ name: "Iraq", code: "IQ", dial: "964" },
	{ name: "Ireland", code: "IE", dial: "353" },
	{ name: "Israel", code: "IL", dial: "972" },
	{ name: "Italy", code: "IT", dial: "39" },
	{ name: "Japan", code: "JP", dial: "81" },
	{ name: "Jordan", code: "JO", dial: "962" },
	{ name: "Kenya", code: "KE", dial: "254" },
	{ name: "Kuwait", code: "KW", dial: "965" },
	{ name: "Malaysia", code: "MY", dial: "60" },
	{ name: "Mexico", code: "MX", dial: "52" },
	{ name: "Morocco", code: "MA", dial: "212" },
	{ name: "Nepal", code: "NP", dial: "977" },
	{ name: "Netherlands", code: "NL", dial: "31" },
	{ name: "New Zealand", code: "NZ", dial: "64" },
	{ name: "Nigeria", code: "NG", dial: "234" },
	{ name: "Norway", code: "NO", dial: "47" },
	{ name: "Oman", code: "OM", dial: "968" },
	{ name: "Pakistan", code: "PK", dial: "92" },
	{ name: "Peru", code: "PE", dial: "51" },
	{ name: "Philippines", code: "PH", dial: "63" },
	{ name: "Poland", code: "PL", dial: "48" },
	{ name: "Portugal", code: "PT", dial: "351" },
	{ name: "Qatar", code: "QA", dial: "974" },
	{ name: "Romania", code: "RO", dial: "40" },
	{ name: "Russia", code: "RU", dial: "7" },
	{ name: "Saudi Arabia", code: "SA", dial: "966" },
	{ name: "Singapore", code: "SG", dial: "65" },
	{ name: "South Africa", code: "ZA", dial: "27" },
	{ name: "South Korea", code: "KR", dial: "82" },
	{ name: "Spain", code: "ES", dial: "34" },
	{ name: "Sri Lanka", code: "LK", dial: "94" },
	{ name: "Sweden", code: "SE", dial: "46" },
	{ name: "Switzerland", code: "CH", dial: "41" },
	{ name: "Taiwan", code: "TW", dial: "886" },
	{ name: "Thailand", code: "TH", dial: "66" },
	{ name: "Turkey", code: "TR", dial: "90" },
	{ name: "Ukraine", code: "UA", dial: "380" },
	{ name: "United Arab Emirates", code: "AE", dial: "971" },
	{ name: "United Kingdom", code: "GB", dial: "44" },
	{ name: "United States", code: "US", dial: "1" },
	{ name: "Venezuela", code: "VE", dial: "58" },
	{ name: "Vietnam", code: "VN", dial: "84" },
	{ name: "Zimbabwe", code: "ZW", dial: "263" },
].sort((a, b) => a.name.localeCompare(b.name));
